### ISSUE TITLE
statusreport-period = 0 in config.toml seems not working

### ISSUE THREAD

**Issue by sraue** [threathunters-io/laurel#107]
Hi,

setting statusreport-period = 0 in config.toml seems not to disable the status reports in version 0.4.1. instead it spams syslog several times per second with the status report. older versions i dont have tested.

greetings, Stephan

**Comment by disasmwinnie** [comment]
Can reproduce.

the problem is here: https://github.com/threathunters-io/laurel/blob/5bc800a9d291945d88188fabb07ccf9a2346fb10/src/main.rs#L296

A check if the config param is > 0 should fix the issue.

**Comment by hillu** [comment]
Fix merged.
