### ISSUE TITLE
install laurel offline

### ISSUE THREAD

**Issue by kathyl21** [threathunters-io/laurel#155]
Not sure if this is an issue, but can you install laurel offline?  Don't have internet access on the network we want to install laurel on.

**Comment by hillu** [comment]
Sure. As of today, Laurel itself has no network functionality. You can use your internal deployment mechanisms to install the binary onto the system and configure it as described in the [manual page](https://github.com/threathunters-io/laurel/blob/master/man/laurel.8.md).
