### ISSUE TITLE
Laurel - output send via syslog

### ISSUE THREAD

**Issue by JensJThuering** [threathunters-io/laurel#156]
We found in documentation, that laurel create a local file with the transformed information. (From git project web page: It reads the audit logs from standard input, parses them, and writes a modified form of the audit log to a different log file.)
 
We need a solution to send the tranformed laurel events to a central log instance. Is it possible to create an alternative output destination? We found no way to do this with the laurel solution itself. We use the syslog function inside the audit service and got these messages, but we miss the laurel transformation. 
 
Thanks

**Comment by hillu** [comment]
It should certainly be possible to add Syslog support with little effort: We already use Syslog to log diagnostic and route messages.

Are you able to do a PR for this? (Have a look at `Log` in `main.rs`.)

In the meantime, you should be able to configure rsyslog (or whatever is your standard Syslog software) to collect from the logs that Laurel writes. (Not sure off-hand if journald can be made to do the same thing.)

**Comment by hillu** [comment]
Another thought: The messages generated by Laurel may exceed the maximum length supported by existing Syslog implementations, especially for execve events with long command lines.

**Comment by mkuerschner** [comment]
Hello hillu,

 the usage of rsyslog as input shipper for the log file is smart. I think we will try this option first. 

>Are you able to do a PR for this?
Sorry for asking: What do you mean by "PR" - pull request?

>Another thought: The messages generated by Laurel may exceed the maximum length supported by existing Syslog implementations, especially for execve events with long command lines.

We will use the GELF format and as I see this support up to 20.000 characters (max 32KiB). Do you think this is not enough`

**Comment by hillu** [comment]
> > Are you able to do a PR for this?
> 
> Sorry for asking: What do you mean by "PR" - pull request?

Yes.

> > Another thought: The messages generated by Laurel may exceed the maximum length supported by existing Syslog implementations, especially for execve events with long command lines.
> 
> We will use the GELF format and as I see this support up to 20.000 characters (max 32KiB). Do you think this is not enough?

We have seen longer lines than that, mostly through misuse of find with wildcards, e.g. `find /some/directory/* …` This was the reason for adding `transform.execve-argv-limit-bytes`.

**Comment by hillu** [comment]
I don't think that I am going to implement a direct Syslog output for Laurel since there's always the possibility to pick up logs written to the filesystem using rsyslog or similar software. (I will accept PRs, though.)
