### ISSUE TITLE
For translated values, there should be an option to drop the numeric/binary original values.

### ISSUE THREAD

**Issue by SolitudePy** [threathunters-io/laurel#157]
Example event:
```json
{
    "ID": "1687615922.648:19143",
    "SYSCALL": {
        **"arch": "0xc000003e",**
        "syscall": 59,
        **"success": "yes",**
        "exit": 0,
        "items": 2,
        "ppid": 1653,
        "pid": 15642,
        **"auid": 0,
        "uid": 0,
        "gid": 0,
        "euid": 0,
        "suid": 0,
        "fsuid": 0,
        "egid": 0,
        "sgid": 0,
        "fsgid": 0,**
        "tty": "pts0",
        "ses": 1,
        "comm": "tail",
        "exe": "/usr/bin/tail",
        "subj": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",
        "key": "T1059_1",
        **"ARCH": "x86_64",
        "SYSCALL": "execve",**
        **"AUID": "root",
        "UID": "root",
        "GID": "root",
        "EUID": "root",
        "SUID": "root",
        "FSUID": "root",
        "EGID": "root",
        "SGID": "root",
        "FSGID": "root",**
        "ARGV": ["0x20c9e40", "0x20c1c30", "0x1fd8220", "0x7ffda1ca01e0"],
        "PPID": {
            "comm": "bash",
            "exe": "/usr/bin/bash",
            "ppid": 1647
        },
        "PID": {
            "EVENT_ID": "1687615922.648:19143"
        }
    },
    "EXECVE": {
        "argc": 4,
        "ARGV": ["tail", "-n", "1", "audit.log"],
        "ENV": {}
    },
    "CWD": {
        "cwd": "/var/log/laurel"
    },
    "PATH": [{
        "item": 0,
        "name": "/usr/bin/tail",
        "inode": 50495083,
        "dev": "08:03",
        "mode": "0o100755",
        "ouid": 0,
        "ogid": 0,
        "rdev": "00:00",
        "obj": "system_u:object_r:bin_t:s0",
        "objtype": "NORMAL",
        "cap_fp": "0x0",
        "cap_fi": "0x0",
        "cap_fe": 0,
        "cap_fver": "0x0",
        "OUID": "root",
        "OGID": "root"
    }, {
        "item": 1,
        "name": "/lib64/ld-linux-x86-64.so.2",
        "inode": 201888,
        "dev": "08:03",
        "mode": "0o100755",
        "ouid": 0,
        "ogid": 0,
        "rdev": "00:00",
        "obj": "system_u:object_r:ld_so_t:s0",
        "objtype": "NORMAL",
        "cap_fp": "0x0",
        "cap_fi": "0x0",
        "cap_fe": 0,
        "cap_fver": "0x0",
        "OUID": "root",
        "OGID": "root"
    }],
    "PROCTITLE": {
        "ARGV": ["tail", "-n", "1", "audit.log"]
    }
}
```
there are multiple fields of arch, syscall, *uid etc, one field is resolved(CAPS one) and one isn't(lowercase one)
log_format is set to ENRICHED & translate.UNIVERSAL/translate.user-db is set to false
I also tried to set them the other way around.
How can I get resolved output without unnecessary fields? couldn't find a way to achieve that, thanks ahead

**Comment by hillu** [comment]
What is the result you are looking for – do you want the numeric values that are translated to be dropped, so are you maybe not interested in `auid=0` at all and only want to see `AUID="root"` ?

**Comment by SolitudePy** [comment]
@hillu Yes, exactly

**Comment by SolitudePy** [comment]
@hillu Hey, thank you so much work your work, this is super helpful. 
But, my intention was to have an option to drop all raw values(SYSCALL.arch, SYSCALL.ARGV) and not only raw user ids,
also you could make a configurable list in the config.toml file to choose what fields you would like to drop.
Thanks for your time

**Comment by SolitudePy** [comment]
Thanks, if you look at the sample event I sent u there are more meaningless fields, such as SYSCALL.EXECVE, what do you think abotu that? can it be dropped?

**Comment by hillu** [comment]
> meaningless fields, such as SYSCALL.EXECVE

Do you mean the `"SYSCALL": "execve"` which got translated from `"syscall": 59` ? My patch should drop the lowercase `arch` and `syscall` fields with numeric values.

**Comment by SolitudePy** [comment]
My bad, I meant that for example: 
Under SYSCALL > "ARGV": ["0x20c9e40", "0x20c1c30", "0x1fd8220", "0x7ffda1ca01e0"],

**Comment by hillu** [comment]
It's certainly possible to throw those away, too. I wouldn't do that because I have use-cases that rely on interpreting syscall arguments. So I don't consider SYSCALL.ARGV entirely useless and I'm not going to implement this. I will accept a patch that makes this configurable, though.

**Comment by SolitudePy** [comment]
yeah configurable option would be great, also what use case for example do you have for SYSCALL.ARGV?

**Comment by hillu** [comment]
> what use case for example do you have for SYSCALL.ARGV?

I'll have to double-check for specifics, but there are some rules aound flags for _open(2)_, _socket(2)_, and _clone(2)_.

**Comment by hillu** [comment]
I think I have implemented everything that has been discussed in this issue, except for not outputting SYSCALL.ARGV. If you really have a use-case for that, please open a separate issue.
