### ISSUE TITLE
Let's consider dealing more gracefully with missing EOEs

### ISSUE THREAD

**Issue by hillu** [threathunters-io/laurel#16]
I suppose we could deal with missing end-of-event messages (see #14) more gracefully by changing `Coalesce::process_line` to enqueue objects instead of returning them.

**Comment by Crypt0-M3lon** [comment]
Hi, I tested to use the tool to parse offline event using `cat audit.log | ./laurel`. All lines are correctly read, but the json output is empty. As far as I understand, as my file is missing EOE event type, all events are stuck in the `Coalesce.inflight` variable. My level in rust is non-existent but could it be possible to empty the buffer and write all waiting events at shutdown ?

**Comment by hillu** [comment]
> could it be possible to empty the buffer and write all waiting events at shutdown ?
Yes, this would be possible. I'm have been working on a change that would make timeout-based flushing of `inflight` easier.

**Comment by Crypt0-M3lon** [comment]
From the documentation, EOE is not always the last generated event when working with event streams. Maybe implementing this logic could be a solution:
```
     The auditd system does not guarantee that the records that make
       up an event will appear in order. Thus, when processing event
       streams, we need to maintain a list of events with their own list
       of records hence List of List (LOL) event processing.

       When processing an event stream we define the end of an event via

              record type = AUDIT_EOE (audit end of event type record),
              or
              record type = AUDIT_PROCTITLE (we note the AUDIT_PROCTITLE
              is always the last record), or
              record type = AUDIT_KERNEL (kernel events are one record
              events), or
              record type < AUDIT_FIRST_EVENT (only single record events
              appear before this type), or
              record type >= AUDIT_FIRST_ANOM_MSG (only single record
              events appear after this type), or
              record type >= AUDIT_MAC_UNLBL_ALLOW && record type <=
              AUDIT_MAC_CALIPSO_DEL (these are also one record events),
              or
              for the stream being processed, the time of the event is
              over end_of_event_timeout seconds old.
```

**Comment by hillu** [comment]
> From the documentation, EOE is not always the last generated event

Can you provide a reference for this? At least for events generated by a syscall or filesystem watch actions, I'm pretty sure that they start with SYSCALL and end with EOE lines.

**Comment by Crypt0-M3lon** [comment]
It is my interpretation from the cited lines and observation on my machine, I have never seen any EOE logs.

**Comment by hillu** [comment]
> It is my interpretation from the cited lines and observation on my machine, I have never seen any EOE logs.

Ah, I see. EOE messages are generated by the kernel. They are not written to the regular logfile by _auditd_, but they are passed on through the Audit Dispatcher ("audisp") interface that is used by _LAUREL_ so far.

**Comment by Crypt0-M3lon** [comment]
Oh okay, it explains a lot. I try to use Laurel on log files collected on endpoint, works well but missing EOE IS breaking the output. A small dirty patch replacing EOE by PROCTITLE on my side did the job but it cannot be a long term solution.

**Comment by jgru** [comment]
> Ah, I see. EOE messages are generated by the kernel. They are not written to the regular logfile by auditd, but they are passed on through the Audit Dispatcher ("audisp") interface that is used by LAUREL so far.

Can you somehow force, that the `auditd` writes EOE messages into `audit.log` as well? 
If not, do you think it would make sense to patch `auditd` to do so?
 
In my use case I want to be able to parse existing `audit.log`s with `laurel` like `cat /var/log/audit.log | ./laurel > audit.log.jsonl`, which is not possible due to the missing EOE messages right now.

**Comment by hillu** [comment]
I think one would need to patch auditd.

I have a patch ready that fixes this in _LAUREL_, though.

**Comment by jgru** [comment]
> I think one would need to patch auditd.

Thanks for the clarification. 

> I have a patch ready that fixes this in _LAUREL_, though.

Those are some good news. Looking forward for the update. Can you give a hint how long we have to wait for it?
Thanks for providing _LAUREL_ and developing it actively!

**Comment by hillu** [comment]
> Can you give a hint how long we have to wait for it?

A couple of days at most.
