### ISSUE TITLE
Add Hostname to JSON log

### ISSUE THREAD

**Issue by chrisanag1985** [threathunters-io/laurel#165]
Can the hostname be added as a field in the JSON log? Thanks in advance.

**Comment by hillu** [comment]
Just configure _auditd_ to include the hostname, look for `name_format` in the `auditd.conf` manpage.

**Comment by chrisanag1985** [comment]
Thank you for your fast reply...

**Comment by hillu** [comment]
Does this do what you intended?

**Comment by chrisanag1985** [comment]
Yes... it is exactly what i was looking for.... Thanks again.
