### ISSUE TITLE
SELinux policy for RHEL8 fails

### ISSUE THREAD

**Issue by 0xFustang** [threathunters-io/laurel#174]
### Description

While installing Laurel on RHEL8 with SELinux enforced, Auditd is unable to run laurel plugin.  

Steps to reproduce:

1. Install RHEL8 and set SELinux policy to enforced
2. Reboot
3. Follow Laurel installation including the SELinux policy installation
4. Restart Auditd and check the AVC logs

Logs:

```
Nov 16 16:06:35 rhel8 systemd[1]: Starting Security Auditing Service...
Nov 16 16:06:35 rhel8 auditd[838]: Error opening /etc/audit/plugins.d//af_unix.conf (Permission denied)
Nov 16 16:06:35 rhel8 auditd[838]: Skipping af_unix.conf plugin due to errors
Nov 16 16:06:35 rhel8 auditd[838]: Error opening /etc/audit/plugins.d//laurel.conf (Permission denied)
Nov 16 16:06:35 rhel8 auditd[838]: Skipping laurel.conf plugin due to errors
Nov 16 16:06:35 rhel8 auditd[838]: No plugins found, not dispatching events
Nov 16 16:06:35 rhel8 kernel: audit: type=1400 audit(1700147195.733:4): avc:  denied  { dac_read_search } for  pid=838 comm="auditd" capability=2  scontext=system_u:system_r:auditd_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=capability permissive=0
Nov 16 16:06:35 rhel8 kernel: audit: type=1400 audit(1700147195.734:5): avc:  denied  { dac_override } for  pid=838 comm="auditd" capability=1  scontext=system_u:system_r:auditd_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=capability permissive=0
Nov 16 16:06:35 rhel8 kernel: audit: type=1400 audit(1700147195.734:6): avc:  denied  { dac_read_search } for  pid=838 comm="auditd" capability=2  scontext=system_u:system_r:auditd_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=capability permissive=0
Nov 16 16:06:35 rhel8 kernel: audit: type=1400 audit(1700147195.734:7): avc:  denied  { dac_override } for  pid=838 comm="auditd" capability=1  scontext=system_u:system_r:auditd_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=capability permissive=0
Nov 16 16:06:35 rhel8 auditd[838]: Init complete, auditd 3.0.7 listening for events (startup state enable)
```

**Comment by hillu** [comment]
There's a SELinux policy for Laurel in `contrib/selinux` that assigns a new type `laurel_t` to laurel if spawned by auditd. If you install that on your system, those errors should go away.

**Comment by 0xFustang** [comment]
Hi @hillu! I followed the steps and installed the SELinux policy - I ran into the errors I've described

**Comment by hillu** [comment]
Did you label your laurel binary?

**Comment by hillu** [comment]
my best guess is that `/etc/audit/plugins.d` or the files therein are not labelled correctly. What does
```
ls -lZ /etc/audit/plugins.d/
```
tell you?

**Comment by 0xFustang** [comment]
It says...:

```
# ls -lZ /etc/audit/plugins.d/
total 8
-rw-r-----. 1 root root system_u:object_r:auditd_etc_t:s0 358 Jun 29 08:13 af_unix.conf
-rw-------. 1 root root system_u:object_r:auditd_etc_t:s0 128 Nov 16 14:33 laurel.conf
```

Do you think it has to do with SE

**Comment by hillu** [comment]
> Do you think it has to do with Audit not able to reach the plugin config?

Yeah. `auditd[838]: Error opening […] (Permission denied)` is a pretty strong hint, I'd say.

**Comment by hillu** [comment]
Is the auditd binary labelled properly?

**Comment by 0xFustang** [comment]
Let me know if this is helpful 😄 

Auditd binary label

```
$ ls -lZ /usr/sbin/auditd
-rwxr-xr-x. 1 root root system_u:object_r:auditd_exec_t:s0 159528 Jun 29 08:13 /usr/sbin/auditd
```

Running auditd process:
```
# ps -eZ | grep audit
system_u:system_r:kernel_t:s0        28 ?        00:00:00 kauditd
system_u:system_r:auditd_t:s0       840 ?        00:00:00 auditd
system_u:system_r:kernel_t:s0       859 ?        00:00:00 audit_prune_tre
```

**Comment by 0xFustang** [comment]
Thanks... I will investigate more on my RHEL8 box, the command you mentioned above didn't worked. I'll check!!

**Comment by hillu** [comment]
If you have another machine or VM to try things on, try this (without installing Laurel at all): Just try enabling the `af_unix` plugin.

**Comment by 0xFustang** [comment]
Hi @hillu, the error was on my side (of course). When I applied a`chmod 740 /etc/audit/plugins.d/ -R` it worked out... This was probably because I messed up the chmod part in my Ansible task. Sorry for the trouble! 😭
