### ISSUE TITLE
aarch64 builds missing since v0.5.4

### ISSUE THREAD

**Issue by MaZderMind** [threathunters-io/laurel#180]
Since [v0.5.4](https://github.com/threathunters-io/laurel/releases/tag/v0.5.4) no aarch64 releases are available from the download page. v0.5.3 is the last aarch64 version.

Is this intended or a side-product of some unexpected changes?

**Comment by hillu** [comment]
Sorry; building aarch64 binaries had been a manual effort and I just had not gotten around to adding those builds.

**Comment by MaZderMind** [comment]
Oh, sorry then, I did not realise that.

**Comment by hillu** [comment]
No worries, I just found some tuits and uploaded tarballs for aarch64 builds.

**Comment by MaZderMind** [comment]
Hey there! Is there a reason not to build the aarch64 images using a github workflow? If you could drop your current build process into a snippet somewhere I'd love to integrate them into the workflow and send a PR.

**Comment by MaZderMind** [comment]
Are you sure? GitHub announced macOS M1 aarch64 runners in October last year:
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

According to the pricing sheet I would expect the small runners to even be available in the free tier:
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

**Comment by hillu** [comment]
I have found a way to do glibc (>= 2.28) cross-builds in CI using Debian's multiarch support. armv7 and aarch64 builds have been added to the 0.6.2 release. Please reopen if you find problems with those.
