### ISSUE TITLE
PPID is not always generated

### ISSUE THREAD

**Issue by n9** [threathunters-io/laurel#188]
One message with PPID present:

> {"ID":"1704898413.743:224129",
"SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":3,**"ppid":614,"pid":3566071**,"auid":4294967295,"uid":0,"gid":0,"euid":0,"suid":0,"fsuid":0,"egid":0,"sgid":0,"fsgid":0,"tty":"(none)","ses":4294967295,"comm":"iptables-restor","exe":"/usr/sbin/xtables-nft-multi","subj":"unconfined","key":"executed-files","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"root","GID":"root","EUID":"root","SUID":"root","FSUID":"root","EGID":"root","SGID":"root","FSGID":"root","ARGV":["0xc000949000","0xc00104fc40","0xc000dc4b00","0x0"],
**"PPID":{"START_TIME":"1698832112.932","comm":"kube-router","exe":"/opt/kube-router/kube-router","ppid":1},
"PID":{"EVENT_ID":"1704898413.743:224129"}},**
"EXECVE":{"argc":3,"ARGV":["iptables-restore","-T","filter"],"ENV":{}},
"CWD":{"cwd":"/"},
"PATH":[{"item":0,"name":"/usr/sbin/iptables-restore","inode":789498,"dev":"08:01","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/usr/sbin/iptables-restore","inode":815240,"dev":"08:01","mode":"0o120777","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":2,"name":"/lib64/ld-linux-x86-64.so.2","inode":800548,"dev":"08:01","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],
"PROCTITLE":{"ARGV":["iptables-restore","-T","filter"]}}

The next message does not contain PPID, but pid and ppid are same:

> {"ID":"1704898413.751:224130",
"NETFILTER_CFG":[{"table":"filter:20643","family":2,"entries":240,"op":"nft_register_chain","pid":3566071,"subj":"unconfined","comm":"iptables-restor"},{"table":"filter:20643","family":2,"entries":237,"op":"nft_unregister_table","pid":3566071,"subj":"unconfined","comm":"iptables-restor"}],
"SYSCALL":{"arch":"0xc000003e","syscall":46,"success":"yes","exit":137972,"items":0,**"ppid":614,"pid":3566071**,"auid":4294967295,"uid":0,"gid":0,"euid":0,"suid":0,"fsuid":0,"egid":0,"sgid":0,"fsgid":0,"tty":"(none)","ses":4294967295,"comm":"iptables-restor","exe":"/usr/sbin/xtables-nft-multi","subj":"unconfined","key":null,"ARCH":"x86_64","SYSCALL":"sendmsg","AUID":"unset","UID":"root","GID":"root","EUID":"root","SUID":"root","FSUID":"root","EGID":"root","SGID":"root","FSGID":"root","ARGV":["0x3","0x7ffc4606e510","0x0","0x7ffc4606e4fc"],
**"PID":{"EVENT_ID":"1704898413.743:224129"}**
},"SOCKADDR":[{"saddr":"%10%00%00%00%00%00%00%00%00%00%00%00","SADDR":"{saddr_fam=netlink nlnk-fam=16 nlnk-pid=0}"}],"PROCTITLE":{"ARGV":["iptables-restore","-T","filter"]}}

Auditd logs:
```
type=SYSCALL msg=audit(1704898413.743:224129): arch=c000003e syscall=59 success=yes exit=0 a0=c000949000 a1=c00104fc40 a2=c000dc4b00 a3=0 items=3 ppid=614 pid=3566071 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables-restor" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key="executed-files"ARCH=x86_64 SYSCALL=execve AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=EXECVE msg=audit(1704898413.743:224129): argc=3 a0="iptables-restore" a1="-T" a2="filter"
type=CWD msg=audit(1704898413.743:224129): cwd="/"
type=PATH msg=audit(1704898413.743:224129): item=0 name="/usr/sbin/iptables-restore" inode=789498 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PATH msg=audit(1704898413.743:224129): item=1 name="/usr/sbin/iptables-restore" inode=815240 dev=08:01 mode=0120777 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PATH msg=audit(1704898413.743:224129): item=2 name="/lib64/ld-linux-x86-64.so.2" inode=800548 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PROCTITLE msg=audit(1704898413.743:224129): proctitle=69707461626C65732D726573746F7265002D540066696C746572
```
```
type=NETFILTER_CFG msg=audit(1704898413.751:224130): table=filter:20643 family=2 entries=240 op=nft_register_chain pid=3566071 subj=unconfined comm="iptables-restor"
type=NETFILTER_CFG msg=audit(1704898413.751:224130): table=filter:20643 family=2 entries=237 op=nft_unregister_table pid=3566071 subj=unconfined comm="iptables-restor"
type=SYSCALL msg=audit(1704898413.751:224130): arch=c000003e syscall=46 success=yes exit=137972 a0=3 a1=7ffc4606e510 a2=0 a3=7ffc4606e4fc items=0 ppid=614 pid=3566071 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables-restor" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key=(null)ARCH=x86_64 SYSCALL=sendmsg AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=SOCKADDR msg=audit(1704898413.751:224130): saddr=100000000000000000000000SADDR={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 }
type=PROCTITLE msg=audit(1704898413.751:224130): proctitle=69707461626C65732D726573746F7265002D540066696C746572
```

### Next examples

With PPID:

> {"ID":"1704905084.824:233823","SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":2,**"ppid":3519858,"pid":3570448**,"auid":4294967295,"uid":0,"gid":0,"euid":0,"suid":0,"fsuid":0,"egid":0,"sgid":0,"fsgid":0,"tty":"(none)","ses":4294967295,"comm":"runc","exe":"/usr/local/sbin/runc","subj":"unconfined","key":"executed-files","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"root","GID":"root","EUID":"root","SUID":"root","FSUID":"root","EGID":"root","SGID":"root","FSGID":"root","ARGV":["0xc00003a5e8","0xc0002b76e0","0xc0000349a0","0x0"],**"PPID":{"EVENT_ID":"1704829408.179:122565","comm":"containerd-shim","exe":"/usr/local/bin/containerd-shim-runc-v2","ppid":1},"PID":{"EVENT_ID":"1704905084.824:233823"}**},"EXECVE":{"argc":10,"ARGV":["runc","--root","/run/containerd/runc/k8s.io","--log","/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3cd41e466eb666b270982e489bb5fa3f17a31004cb4333b4702973a7c369b4d/log.json","--log-format","json","--systemd-cgroup","delete","a3cd41e466eb666b270982e489bb5fa3f17a31004cb4333b4702973a7c369b4d"],"ENV":{"LD_LIBRARY_PATH":"/opt/containerd/lib:"}},"CWD":{"cwd":"/run/containerd/io.containerd.runtime.v2.task/k8s.io/1cfc86964c51e3731e5f11382354c8bceb5a5de8083cb5e312276e80696cc960"},"PATH":[{"item":0,"name":"/usr/local/sbin/runc","inode":913958,"dev":"08:01","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/usr/local/sbin/runc","inode":913958,"dev":"08:01","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["runc","--root","/run/containerd/runc/k8s.io","--log","/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3cd41e466eb666b270982e489bb5"]}}

Without PPID:

> {"ID":"1704905084.828:233825","SYSCALL":{"arch":"0xc000003e","syscall":257,"success":"yes","exit":3,"items":2,**"ppid":3519858,"pid":3570448**,"auid":4294967295,"uid":0,"gid":0,"euid":0,"suid":0,"fsuid":0,"egid":0,"sgid":0,"fsgid":0,"tty":"(none)","ses":4294967295,"comm":"runc","exe":"/usr/local/sbin/runc","subj":"unconfined","key":"opens-to-modify","ARCH":"x86_64","SYSCALL":"openat","AUID":"unset","UID":"root","GID":"root","EUID":"root","SUID":"root","FSUID":"root","EGID":"root","SGID":"root","FSGID":"root","ARGV":["0xffffffffffffff9c","0xc0000b2e80","0x181441","0x1a4"],**"PID":{"EVENT_ID":"1704905084.824:233823"}**},"CWD":{"cwd":"/run/containerd/io.containerd.runtime.v2.task/k8s.io/1cfc86964c51e3731e5f11382354c8bceb5a5de8083cb5e312276e80696cc960"},"PATH":[{"item":0,"name":"/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3cd41e466eb666b270982e489bb5fa3f17a31004cb4333b4702973a7c369b4d/","inode":1025813,"dev":"00:17","mode":"0o40700","ouid":0,"ogid":0,"rdev":"00:00","nametype":"PARENT","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3cd41e466eb666b270982e489bb5fa3f17a31004cb4333b4702973a7c369b4d/log.json","inode":1025822,"dev":"00:17","mode":"0o100644","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["runc","--root","/run/containerd/runc/k8s.io","--log","/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3cd41e466eb666b270982e489bb5"]}}

**Comment by n9** [comment]
@hillu Thank you.

https://github.com/threathunters-io/laurel/pull/189 seems to fix the issue.

**Comment by hillu** [comment]
@n9 Yeah, I stumbled across that bug this week, too. Sorry about that, I'll release 0.5.6 shortly.

**Comment by n9** [comment]
> Sorry about that, I'll release 0.5.6 shortly.

Take your time. I am not using official releases.
