### ISSUE TITLE
Advanced filtering (by regexes?)

### ISSUE THREAD

**Issue by n9** [threathunters-io/laurel#190]
Auditd filtering is somewhat limited, for example: `-F path!=...` seems not to be supported (`Invalid argument`). Certain situations can be solved by adding extra rules with `exclude`. However, this will not work if the path does not exist (`No such file or directory`).

What about adding a possibility to filter raw auditd records by regexes (if a regex matches, event will be discarded)?

**Comment by hillu** [comment]
Interesting idea. Would you like Laurel to act as if it hadn't seen a line if that line matches a regex? Or would you like to discard the entire event?

Can you describe more specific use-cases?

**Comment by n9** [comment]
> Would you like Laurel to act as if it hadn't seen a line if that line matches a regex? Or would you like to discard the entire event?

It would discard entire event.

Regexes could be applied only to specific record types, for example: if auditd record has `type=PATH`, then only regex for PATH type will be tested.

> Can you describe more specific use-cases?

For example, to filter out noisy events about attempts to connect to `/var/run/nscd/socket`. (In my case, `/var/run/nscd/socket` does not exist, so it seems to me that these events cannot be filtered by auditd.)

**Comment by hillu** [comment]
So, let's specify the regexp covering that PATH record as part of a list, like so…
``` toml
filter-raw-events = [
    "^type=PATH msg=\\S*? item=\\S*? name=\"/var/run/nscd[.]sock\" "
]
```
The parser would still tokenize the line, but once node+msgid  are determined the entire event is marked to be discarded (or written to `filtered.log`).

Would this work for you?
