### ISSUE TITLE
Missing CONTAINER_INFO in a child process

### ISSUE THREAD

**Issue by n9** [threathunters-io/laurel#191]
A message for **pid** `2992324` with CONTAINER_INFO:

> {"ID":"1704965073.866:327930","SYSCALL":{"arch":"0xc000003e","syscall":2,"success":"yes","exit":3,"items":2,"ppid":2992113,**"pid":2992324**,"auid":4294967295,"uid":1000,"gid":1000,"euid":1000,"suid":1000,"fsuid":1000,"egid":1000,"sgid":1000,"fsgid":1000,"tty":"(none)","ses":4294967295,"comm":"buildctl-daemon","exe":"/bin/busybox","subj":"unconfined","key":"opens-to-modify","ARCH":"x86_64","SYSCALL":"open","AUID":"unset","UID":"unknown(1000)","GID":"unknown(1000)","EUID":"unknown(1000)","SUID":"unknown(1000)","FSUID":"unknown(1000)","EGID":"unknown(1000)","SGID":"unknown(1000)","FSGID":"unknown(1000)","ARGV":["0x7f8609c09248","0x8241","0x1b6","0x0"],"PPID":{"EVENT_ID":"1704965066.218:324295","comm":"containerd-shim","exe":"/usr/local/bin/containerd-shim-runc-v2","ppid":1},"PID":{"EVENT_ID":"1704965073.858:327909"}},"CWD":{"cwd":"/work"},"PATH":[{"item":0,"name":"/dev/","inode":1,"dev":"00:e7","mode":"0o40755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"PARENT","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/dev/null","inode":6,"dev":"00:e7","mode":"0o20666","ouid":0,"ogid":0,"rdev":"01:03","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["runc","init"]},"CONTAINER_INFO":{"ID":"59ff48706b9c0279923d535767878597aedffe88813b297daccfe8b3b6adc914"}}

The next message with  **ppid** `2992324`:

> {"ID":"1704965073.866:327931","SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":2,**"ppid":2992324**,"pid":2992342,"auid":4294967295,"uid":1000,"gid":1000,"euid":1000,"suid":1000,"fsuid":1000,"egid":1000,"sgid":1000,"fsgid":1000,"tty":"(none)","ses":4294967295,"comm":"buildctl","exe":"/usr/bin/buildctl","subj":"unconfined","key":"executed-files","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"unknown(1000)","GID":"unknown(1000)","EUID":"unknown(1000)","SUID":"unknown(1000)","FSUID":"unknown(1000)","EGID":"unknown(1000)","SGID":"unknown(1000)","FSGID":"unknown(1000)","ARGV":["0x7f8609c09470","0x7f8609c09220","0x7f8609c093b8","0x7f8609c095fc"],"PPID":{"EVENT_ID":"1704965073.858:327909","comm":"buildctl-daemon","exe":"/bin/busybox","ppid":2992113},"PID":{"EVENT_ID":"1704965073.866:327931"}},"EXECVE":{"argc":4,"ARGV":["buildctl","--addr=unix:///run/user/1000/buildkit/buildkitd.sock","debug","workers"]},"CWD":{"cwd":"/work"},"PATH":[{"item":0,"name":"/usr/bin/buildctl","inode":5125199,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/usr/bin/buildctl","inode":5125199,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["buildctl","--addr=unix:///run/user/1000/buildkit/buildkitd.sock","debug","workers"]}}

The next message has no CONTAINER_INFO.

The child process exited after 24ms. Laurel may not have a chance to read a cgroup from the procfs?

What about adding an inherited container info? (Inherited from an ancestor, not just the direct parent.)

**Comment by hillu** [comment]
Spot on. Currently, laurel only looks at `/proc/<pid>/cgroup` which may be gone if the process does not live long enough. Inherting from the parent process as a fallback if the proc file is gone seems like a good idea to me. What do you mean by "ancestor"?

**Comment by n9** [comment]
> What do you mean by "ancestor"?

parent, grandparent, ...

It may happen that a short-lived process could spawn another short-lived process.

**Comment by hillu** [comment]
@n9 If you could give my fix a quick test, I'd appreciate it. :-)

**Comment by n9** [comment]
Hmm, it does not seem to work.

I'll check it out, if I find the cause elsewhere, I'll let you know.

**Comment by hillu** [comment]
I have been doing tests on Debian/stable with docker 20.10 and podman 4.3.1. The kernel is recent enough that the kernel-based overlay filesystem is available – and I have verified that docker and podman are making use of the overlay filesystem.
I remember having problems with [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) because that did not allow outside processes to inspect `/proc/$PID/root`.

**Comment by hillu** [comment]
Can you access `/proc/$PID/root` for a process running in a container from outside?

**Comment by hillu** [comment]
The overlay filesystem probably has nothing to do with it… but can you access /proc/$PID/* for any processes running in a container?

**Comment by n9** [comment]
Yes and the `CONTAINER_INFO` is usually present. (But in some cases not, I am investigating how these cases are different.)

**Comment by hillu** [comment]
Perhaps you could add some log statements and use the setup from `contrib/debug` to run a second instance that tells you what it can't access or what it has read.

**Comment by n9** [comment]
Ok. I'll try. 

I just save here few samples.

#### PID 2992342 with PPID 2992324 without CONTAINER_INFO

> {"ID":"1704965073.866:327931","SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":2,"ppid":2992324,"pid":2992342,"auid":4294967295,"uid":1000,"gid":1000,"euid":1000,"suid":1000,"fsuid":1000,"egid":1000,"sgid":1000,"fsgid":1000,"tty":"(none)","ses":4294967295,"comm":"buildctl","exe":"/usr/bin/buildctl","subj":"unconfined","key":"executed-files","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"unknown(1000)","GID":"unknown(1000)","EUID":"unknown(1000)","SUID":"unknown(1000)","FSUID":"unknown(1000)","EGID":"unknown(1000)","SGID":"unknown(1000)","FSGID":"unknown(1000)","ARGV":["0x7f8609c09470","0x7f8609c09220","0x7f8609c093b8","0x7f8609c095fc"],"PPID":{"EVENT_ID":"1704965073.858:327909","comm":"buildctl-daemon","exe":"/bin/busybox","ppid":2992113},"PID":{"EVENT_ID":"1704965073.866:327931"}},"EXECVE":{"argc":4,"ARGV":["buildctl","--addr=unix:///run/user/1000/buildkit/buildkitd.sock","debug","workers"]},"CWD":{"cwd":"/work"},"PATH":[{"item":0,"name":"/usr/bin/buildctl","inode":5125199,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/usr/bin/buildctl","inode":5125199,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["buildctl","--addr=unix:///run/user/1000/buildkit/buildkitd.sock","debug","workers"]}}


#### PID 2992340 with PPID 2992324 with CONTAINER_INFO

> {"ID":"1704965073.862:327929","SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":2,"ppid":2992324,"pid":2992340,"auid":4294967295,"uid":1000,"gid":1000,"euid":1000,"suid":1000,"fsuid":1000,"egid":1000,"sgid":1000,"fsgid":1000,"tty":"(none)","ses":4294967295,"comm":"rootlesskit","exe":"/usr/bin/rootlesskit","subj":"unconfined","key":"executed-files","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"unknown(1000)","GID":"unknown(1000)","EUID":"unknown(1000)","SUID":"unknown(1000)","FSUID":"unknown(1000)","EGID":"unknown(1000)","SGID":"unknown(1000)","FSGID":"unknown(1000)","ARGV":["0x7f8609c09470","0x7f8609c09230","0x7f8609c093b8","0x7f8609c095fc"],"PPID":{"EVENT_ID":"1704965073.858:327909","comm":"buildctl-daemon","exe":"/bin/busybox","ppid":2992113},"PID":{"EVENT_ID":"1704965073.862:327929"}},"EXECVE":{"argc":4,"ARGV":["rootlesskit","buildkitd","--oci-worker-no-process-sandbox","--addr=unix:///run/user/1000/buildkit/buildkitd.sock"],"ENV":{}},"CWD":{"cwd":"/work"},"PATH":[{"item":0,"name":"/usr/bin/rootlesskit","inode":5125187,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/usr/bin/rootlesskit","inode":5125187,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["/bin/sh","/usr/bin/buildctl-daemonless.sh","build","--frontend","dockerfile.v0",...]},"CONTAINER_INFO":{"ID":"59ff48706b9c0279923d535767878597aedffe88813b297daccfe8b3b6adc914"}}

#### Their parent PID 2992324 with CONTAINER_INFO

> {"ID":"1704965073.858:327909","SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":4,"ppid":2992113,"pid":2992324,"auid":4294967295,"uid":1000,"gid":1000,"euid":1000,"suid":1000,"fsuid":1000,"egid":1000,"sgid":1000,"fsgid":1000,"tty":"(none)","ses":4294967295,"comm":"buildctl-daemon","exe":"/bin/busybox","subj":"unconfined","key":"executed-files","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"unknown(1000)","GID":"unknown(1000)","EUID":"unknown(1000)","SUID":"unknown(1000)","FSUID":"unknown(1000)","EGID":"unknown(1000)","SGID":"unknown(1000)","FSGID":"unknown(1000)","ARGV":["0xc00002e9e0","0xc0000bb900","0xc0001ae580","0x0"],"PPID":{"EVENT_ID":"1704965066.218:324295","comm":"containerd-shim","exe":"/usr/local/bin/containerd-shim-runc-v2","ppid":1},"PID":{"EVENT_ID":"1704965073.858:327909"}},"EXECVE":{"argc":19,"ARGV":["/bin/sh","/usr/bin/buildctl-daemonless.sh","build","--frontend","dockerfile.v0",...],"ENV":{}},"CWD":{"cwd":"/work"},"PATH":[{"item":0,"name":"/usr/bin/buildctl-daemonless.sh","inode":5149472,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":1,"name":"/usr/bin/buildctl-daemonless.sh","inode":5149472,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":2,"name":"/bin/sh","inode":5125208,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"},{"item":3,"name":"/lib/ld-musl-x86_64.so.1","inode":5127446,"dev":"00:e4","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["runc","init"]},"CONTAINER_INFO":{"ID":"59ff48706b9c0279923d535767878597aedffe88813b297daccfe8b3b6adc914"}}
