### ISSUE TITLE
SELinux Policy failing to install on Debian

### ISSUE THREAD

**Issue by bootlesshacker** [threathunters-io/laurel#198]
Hi
I'm assuming this issue is related to the fact I'm using SELinux on Debian as I only recently got this installed without issue on an RHEL based distro, but I am having issues with the following command on Debian:

semodule -i contrib/selinux/laurel.pp

The error returned is something along the lines of:
Failed to resolve typeattributeset statement at /var/lib/selinux/default/tmp/modules/400/laurel/cil:37
Failed to resolve AST
semodule:  Failed!

Looking at the policy .te file, the offending line seems to be:
gen_require('type passwd_file_t;')

Removing this line seems to resolve the issue but I'm assuming this line is there for a reason.

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

Do you have any suggestions?

**Comment by hillu** [comment]
My impression is that SELinux is not well-supported on Debian. This probably has to do with Canonical choosing AppArmor over SELinux for their supported products.

I have been able to reproduce your problem on a fresh Debian/bookworm installation. Replacing `passwd_file_t` with `etc_t` ought to help.

**Comment by hillu** [comment]
> I did start looking into AppArmor as I was experiencing issues with another tool too with SELinux.

If you run into issues with the provided AppArmor policy or if you have suggestions on how to improve it, I'd appreciate any feedback.

> I'll test your suggestion when I can and let you know, but I think allowing etc_t might be a bit broad - I'm not sure if this would allow more access than intended?

We only allow open, read operations for those files, so this should be fine. Not everything in /etc is labeled `etc_t`, there's still `shadow_t` for the shadow password file, for instance.
