### ISSUE TITLE
License compliance with MPL2.0

### ISSUE THREAD

**Issue by jorgehermo9** [threathunters-io/laurel#224]
Hi, I would like to use the auditd parser (https://github.com/threathunters-io/laurel/blob/master/src/parser.rs) in https://github.com/vectordotdev/vrl and https://github.com/vectordotdev/vector, but those two projects are MPL-2.0 licensed, which is incompatible with the GPL3.0 of this crate.

Is there any specific reason to use the GPL3.0? Could you consider to relax the licensing restrictions with the adoption Apache or MIT licenses, for example? This could help to widen the usage of this crate.

At least, I think it would be interesting to relax the license for the parser code (maybe in another crate?) since I think this is the most mature parser crate for auditd.

**Comment by hillu** [comment]
I have been meaning to split off the parser code into its own crate for some time. I'm going to do that this weekend. Would LGPL 3.0 work for you?

**Comment by jorgehermo9** [comment]
That would be really awesome I will could help/contribute to that crate if you need a hand. Thank you very much for your quick response.

I think a non-LGPL crate (In this case, MPL-2.0) comply with LGPL crates as dependencies, so the LGPL3.0 will work. I'm not an expert in licensing tho, any thoughts @jszwedko related to Vector's license requirements?

**Comment by hillu** [comment]
@jorgehermo9 Here you go: https://github.com/hillu/linux-audit-parser-rs / https://crates.io/crates/linux-audit-parser

**Comment by jorgehermo9** [comment]
That's awesome @hillu!! 😮 so fast.

If you don't mind, maybe I'll submit a PR these days to your crate for some behaviour I found weird. Specifically, I see that the kernel msg field (the second msg field that appears in the logs) is parsed as a raw string, although it is a key value string itself and can be parsed "nested". Do you know what I mean?

**Comment by hillu** [comment]
> If you don't mind, maybe I'll submit a PR these days to your crate for some behaviour I found weird

Sure, let's continue discussing that in the context of the split-off project.

**Comment by jszwedko** [comment]
Thanks for splitting off the parser to a separate crate @hillu !

While LGPL 3.0 for dependencies is technically compatible with Vector and VRL's license of MPL 2.0, my understanding is that it would restrict the ways in which Vector and VRL could be used further than the MPL 2.0 license currently restricts. My understanding is that users using Vector or VRL in their own projects that they distribute would need to either open source their code with an acceptable license or distribute the resulting artifacts in a way that the LGPL code could be modified and reincluded. Is there any chance you'd consider a more permissive license like MIT, Apache-2.0, or BSD for https://github.com/hillu/linux-audit-parser-rs? I definitely understand if not, but figured it didn't hurt to ask :)
