### ISSUE TITLE
filter-action = "drop" seems to be not working

### ISSUE THREAD

**Issue by SStoegerer** [threathunters-io/laurel#232]
I set **label-exe.'^/opt/splunk/bin/splunk-optimize' = 'test-splunk-optimize'** in the config.toml and this works fine.

## auditd Event
>type=PROCTITLE msg=audit(1733901080.688:1282950): proctitle=73706C756E6B2D6F7074696D697A65002D64002F6F70742F73706C756E6B2F7661722F6C69622F73706C756E6B2F5F696E7465726E616C2F64622F686F745F76315F383238002D78003737383936313432333336002D2D6C6F672D746F2D2D73706C756E6B642D6C6F67002D2D77726974652D6C6576656C0034002D2D747369
type=PATH msg=audit(1733901080.688:1282950): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=5799238 dev=00:1e9 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1733901080.688:1282950): item=0 name="/opt/splunk/bin/splunk-optimize" inode=6708923 dev=00:1e9 mode=0100555 ouid=41812 ogid=41812 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=EXECVE msg=audit(1733901080.688:1282950): argc=12 a0="splunk-optimize" a1="-d" a2="/opt/splunk/var/lib/splunk/_internal/db/hot_v1_828" a3="-x" a4="77896142336" a5="--log-to--splunkd-log" a6="--write-level" a7="4" a8="--tsidx-target-size" a9="1572864000" a10="--msidx-comp-block-size" a11="1024"
type=SYSCALL msg=audit(1733901080.688:1282950): arch=c000003e syscall=59 success=yes exit=0 a0=7ffd8729e710 a1=7ffd8729e800 a2=7ffd872a0f60 a3=8 items=2 ppid=37379 pid=1682025 auid=4294967295 uid=41812 gid=41812 euid=41812 suid=41812 fsuid=41812 egid=41812 sgid=41812 fsgid=41812 tty=(none) ses=4294967295 comm="splunk-optimize" exe="/opt/splunk/bin/splunk-optimize" subj=docker-default key="procexec_64"

## Label applied
>{"ID":"1733901080.688:1282950","SYSCALL":{"arch":"0xc000003e","syscall":59,"success":"yes","exit":0,"items":2,"ppid":37379,"pid":1682025,"auid":4294967295,"uid":41812,"gid":41812,"euid":41812,"suid":41812,"fsuid":41812,"egid":41812,"sgid":41812,"fsgid":41812,"tty":"(none)","ses":4294967295,"comm":"splunk-optimize","exe":"/opt/splunk/bin/splunk-optimize","subj":"docker-default","key":"procexec_64","ARCH":"x86_64","SYSCALL":"execve","AUID":"unset","UID":"unknown(41812)","GID":"unknown(41812)","EUID":"unknown(41812)","SUID":"unknown(41812)","FSUID":"unknown(41812)","EGID":"unknown(41812)","SGID":"unknown(41812)","FSGID":"unknown(41812)","ARGV":["0x7ffd8729e710","0x7ffd8729e800","0x7ffd872a0f60","0x8"],"PPID":{"START_TIME":"1733843330.981","comm":"splunkd","exe":"/opt/splunk/bin/splunkd","ppid":37378},"PID":{"EVENT_ID":"1733901080.688:1282950"},"LABELS":["test-splunk-optimize"]},"EXECVE":{"argc":12,"ARGV":["splunk-optimize","-d","/opt/splunk/var/lib/splunk/_internal/db/hot_v1_828","-x","77896142336","--log-to--splunkd-log","--write-level","4","--tsidx-target-size","1572864000","--msidx-comp-block-size","1024"],"ENV":{"LD_LIBRARY_PATH":"/opt/splunk/lib","LD_PRELOAD":"/opt/splunk/lib/libdlwrapper.so"}},"PATH":[{"item":0,"name":"/opt/splunk/bin/splunk-optimize","inode":6708923,"dev":"00:1e9","mode":"0o100555","ouid":41812,"ogid":41812,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"unknown(41812)","OGID":"unknown(41812)"},{"item":1,"name":"/lib64/ld-linux-x86-64.so.2","inode":5799238,"dev":"00:1e9","mode":"0o100755","ouid":0,"ogid":0,"rdev":"00:00","nametype":"NORMAL","cap_fp":"0x0","cap_fi":"0x0","cap_fe":0,"cap_fver":"0x0","cap_frootid":"0","OUID":"root","OGID":"root"}],"PROCTITLE":{"ARGV":["splunk-optimize","-d","/opt/splunk/var/lib/splunk/_internal/db/hot_v1_828","-x","77896142336","--log-to--splunkd-log","--write-level","4","--tsi"]},"CONTAINER_INFO":{"ID":"445b355b1bedbed33e31641a2292a41f6420789e71d2496dedf2fe5b51dc8cdd"}}

Then I set **filter-labels = ["test-splunk-optimize"]** and **filter-action = "drop"**
It seems that this is not working properly as the events are not filtered. The same behavior occurs with filter-keys and filter-raw-lines.

The config is loaded without errors and there is no information about this in the debug logs either.

Is this a bug, or am I using it incorrectly or overlooking something?

**Comment by hillu** [comment]
Are you using the last released version, 0.6.3, or have you built laurel from git master?

**Comment by SStoegerer** [comment]
I'm using the latest version 0.6.3

**Comment by hillu** [comment]
Sorry for taking so long. I can confirm that this is a bug in Laurel.

For a regular subprocess start using `fork`/`execve`, the `execve` call will be the first event that Laurel sees for the new process, so you should make sure set `filter.keep-first-per-processes` to `false` if you don't want to see this `execve` event at all.

However, this does not work either, at least not with 0.6.3.

**Comment by hillu** [comment]
Oops, this is not a bug in Laurel; my test function behaved as expected and documented. (I was just confused because I didn't look properly at the panic message.)

@SStoegerer please configure `filter.keep-first-per-process = false`. Can you confirm that filtering works as you'd expect with that setting?

**Comment by SStoegerer** [comment]
Thank you very much for checking! However, even with `filter.keep-first-per-process = false` configured, the specified events are still not being filtered.

Could it be because I’m trying to filter events originating from Docker containers? That shouldn’t really matter tho, as the labels are being set correctly, for instance.

However, I tested it on a different system with non-container events, and `filter-keys` is working there. `filter-labels` is still not filtering the events, even with non-container events.

**Comment by hillu** [comment]
Perhaps I was missing something in my test case… Can you share your `/etc/laurel/config.toml` file?

**Comment by SStoegerer** [comment]
[config.toml.gz](https://github.com/user-attachments/files/18147695/config.toml.gz)

**Comment by hillu** [comment]
Oh, it seems that you have fallen victim to a really dumb typo in the configuration file. It's `keep-first-per-processes` (singular).
