### ISSUE TITLE
Processing remotely generated audit events received from au-remote

### ISSUE THREAD

**Issue by jordaneyres** [threathunters-io/laurel#33]
Heya folks,

Is there anything stopping laurel from processing audit logs sent to another server via au-remote? i.e. do audisp plugins require explicit support for remote audit logs, or should it not matter and "just work".

Auditd supports running audisp plugins against remotely received logs using the ```dispatch_network = yes``` config item. I've tested this setting and have gotten it to work with the syslog plugin that ships with Centos, so at least audisp plugins can process logs from remote sources.

Try as I might, I can't seem to get laurel to write out the remote logs; though the locally generated events are working.

Great project by the way, love your work!

**Comment by jordaneyres** [comment]
Correct, hosts a1, a2, a3 have auditd configured and are all using the au-remote audisp plugin to send to a4. a4 is using auditd to listen for incoming logs, and has laurel installed and configured.

Could have been much clearer, sorry about that.

**Comment by hillu** [comment]
I suspect that LAUREL on a4 may be receiving the events on STDIN. You should be able to verify that using strace. If this is the case, the likely explanation for _laurel_ not logging anything is that _auditd_ does not send EOE records via the network (#16).

**Comment by jordaneyres** [comment]
Sounds like a reasonable theory.

As a test, I’ll disable EOE records in the auditd config (on a1) and see what is logged by laurel when installed on a1. If nothing is logged, then that would match what I’m seeing when sent over the network.

**Comment by hillu** [comment]
@jordaneyres I have just pushed a change that removes the EOE requirement (#60). Could you have a look if that helps with your use-case?

**Comment by hillu** [comment]
@jordaneyres ping?

**Comment by hillu** [comment]
@jordaneyres ping?

**Comment by jordaneyres** [comment]
Sorry for the late reply, I’ve just come back from paternity leave.

Will get my lab for this rebuilt and report back with how the changes go.

**Comment by hillu** [comment]
@jordaneyres Did you have time to do further tests?

**Comment by jordaneyres** [comment]
Just finished my initial tests and it appears to work!

Thanks for getting a fix in for this and for your patience waiting for it
to be tested.

Let me know if you would like any further details on the setup.

**Comment by hillu** [comment]
Thanks. I'll close the issue then.
