### ISSUE TITLE
Request to provide a library crate if possible

### ISSUE THREAD

**Issue by kushaldas** [threathunters-io/laurel#37]
Thank you for this useful project.

I am wondering if it will be possible for you to provide a library crate so that other projects can use `laurel` features. This way we don't have to re-invent the wheel and depend on `laurel` as upstream.

Use case I am looking at:  Instead of logging into a file, push to a redis instance or some other queue for processing in a different way.

**Comment by hillu** [comment]
I think we'll be getting there soon. The main obstacle at the moment is figuring out (by having discussions with the compiler) whether Coalesce shout own or mutably borrow the `std::io::Write` thing. :-)

**Comment by hillu** [comment]
@kushaldas As of 18d38cd81653b087ded3625112c03c1328842e84 (or somewhere around that), there is a library. And in 01866e6d1c802d9cfe85b6dae815069e4c6f57fe, I added a commit that you could use to hook up other backends such as Redis.

Can I close this issue?

**Comment by hillu** [comment]
@kushaldas laurel 0.2.0 which has just been released is a library crate that happens to also contain the message recoding tool as before.

Sorry for taking so long with getting this done… Is this what you had in mind?

**Comment by hillu** [comment]
@kushaldas ping?

**Comment by hillu** [comment]
@kushaldas I am closing this issue now.

**Comment by kushaldas** [comment]
Missed all notifications in the last 5-6 months, saw this now. Sorry for not replying. I will try again in the coming week and get back to you with any feedback.

Thank you for doing this.

**Comment by hillu** [comment]
@kushaldas ping?
