### ISSUE TITLE
Feature: add optional field named `CommandLine` concat of ARGV

### ISSUE THREAD

**Issue by Neo23x0** [threathunters-io/laurel#4]
Please add a field (optional) that provides a concatenated full command line

```
"ARGV": ["perl", "-e", "use Socket;$i=\"10.0.0.1\";$p=1234; ...
```

To 
```
"CommandLine": "perl -e use Socket;$i=\"10.0.0.1\";$p=1234; ...
```

e.g.
```
directory = "/var/log/laurel"
user = "_laurel"
concat_command_line = true

[auditlog]
file = "audit.log"
size = 1000000
generations = 10
read-users = [ "splunk" ]
```

**Comment by hillu** [comment]
We'll consider implementing this and would certainly accept pull requests.

Just as a note: For filtering purposes, this can be done efficiently on the SIEM side, e.g. in Splunk:
```
| eval cmdline=urldecode(mvjoin('EXECVE.ARGV{}', " "))
```

**Comment by Neo23x0** [comment]
An `eval` in splunk is a field modification that happens at search time. Most other SIEM systems index fields in the form they receive them and don't provide many or efficient methods to combine, split or modify fields at search time but perform these actions at index time. The problem with that is that this is often a custom modification of the indexer logic and differs from user to user. 

Since we try to write rules that can be used by all users in the same way and the full command line is the single most important field for which we try to develop rules since day 1, a concatenated command line field would be very helpful.

**Comment by d4rk-d4nph3** [comment]
I agree with @Neo23x0 that most other SIEMs (mine too) lack functionality to combine fields at search time. For example, even in ELK you can achieve this by scripting but that is not recommended as it causes performance hit.

**Comment by AndyXan** [comment]
The main reason why LAUREL exists in the first place - because even with splunk, decoding, combining (which requires for-each) on a dynamic list of a0, aX[] fields is not possible. 

However, one thing to keep in mind though: Even with a joined array, For "plaintext" commandlines, `urldecode` is necessary - either at index or searchtime. This cannot be done by LAUREL, otherwise the transfer with json wouldn't be without information loss.
