### ISSUE TITLE
Consider using Nom for parsing

### ISSUE THREAD

**Issue by zmackie** [threathunters-io/laurel#45]
I'm opening this issue in the spirit of a discussion. I'm far from an expert (or even a novice really) with parsing, but I'll give you my reason for asking:
 I was hoping to contribute to `laurel` and (specifically int the parser) and went to learn how `peg` works. I couldn't find a single tutorial. Obviously you guys learned peg to write the code, but I found a huge wealth of material on `nom` and it seems like a much more widely used and embraced parsing library.  I realize this is a bit of a holy war, but for security software, especially parsers, I wonder if using a more widely found library might be considered. (I also find `nom` code - which is not macros) much easier to read and understand.
 Would this change be something you'd consider if somebody contributed it?

**Comment by hillu** [comment]
I have now added a simple benchmark that feeds similar data to a Coalesce object as would be generated by [edr-loadgen](https://github.com/hillu/edr-loadgen). Run with `cargo bench`.

**Comment by zmackie** [comment]
I see what you mean that's its a tedious change especially the [big KV parse `alt` statement ](https://github.com/threathunters-io/laurel/compare/master...hillu:feature/nom-parser?expand=1#diff-4a04259da480a6b794a2e947e4cc03eff4d1aa9330836f5b91cac68c5398193fR237-R293).

I think the code looks solid and fairly idiomatically `nom` from reading other parsers. Personally I find it to be more readable than the `peg` parser, but that's probably just my preference for functions over macros..
If the perf is improved, I'd say its a win! (especially since `nom` is a very active project and will likely see feature and perf gains in the future.

**Comment by hillu** [comment]
@zmackie A remaining problem are error messages if parsing goes wrong, such as
``` json
{"error":{"message":"Parsing Error: Error { input: [106, 97, 115, 107, 108, 100, 102, 106, 115, 97, 107, 100, 108, 106, 102, 115, 100, 97, 107, 108, 106, 102, 115, 100, 97, 108, 107, 115, 10], code: Tag }","input":"jaskldfjsakdljfsdakljfsdalks\n"}}
```
If you have an idea how to do proper error reporting with nom, I'd be grateful for suggestions.

**Comment by hillu** [comment]
@zmackie Would you like to review #58?

**Comment by hillu** [comment]
Closing issue after merging #58
