### ISSUE TITLE
Node attribute lost during parsing

### ISSUE THREAD

**Issue by Crypt0-M3lon** [threathunters-io/laurel#47]
Hi, 

When the event is parsed, the `Node` attribute is not saved: https://github.com/threathunters-io/laurel/blob/master/src/parser.rs#L90
in the end, the information about the host generating the event is lost. Do you think it would be possible to add it to the output json ?

Thanks for this tool, it could be a real timesaver!

**Comment by hillu** [comment]
Sure, possible, probably easy, will do.

**Comment by hillu** [comment]
@Crypt0-M3lon Would you please have a look at #51 to see if it solves this problem for you?
