### ISSUE TITLE
laurel installation Ubuntu 20.04

### ISSUE THREAD

**Issue by laurafbec** [threathunters-io/laurel#54]
Hi everyone
I'm trying to use laurel in Ubuntu 20.04 but I don't know if it's possible to use it in this Linux distribution and how should I do the install process.
Thanks in advance

**Comment by disasmwinnie** [comment]
Hi @laurafbec,
it's pretty much on all Linux distros which run Auditd. Ubuntu 20.04 is definitely on that list. Could you point out what is unclear  about the [install docs](https://github.com/threathunters-io/laurel#configure-use)?

**Comment by laurafbec** [comment]
Thanks @disasmwinnie!! Everything is clear. I've installed laurel and it's working now.  But, I still get de "ARGV" in hex format, is it normal?  Thanks again

`{"ID":"1638262038.968:1144","NODE":"l-VirtualBox","SYSCALL":{"arch":"0xc000003e","syscall":62,"success":"yes","exit":0,"items":0,"ppid":10425,"pid":10426,"auid":1000,"uid":1000,"gid":1000,"euid":1000,"suid":1000,"fsuid":1000,"egid":1000,"sgid":1000,"fsgid":1000,"tty":"pts1","ses":3,"comm":"bash","exe":"/usr/bin/bash","subj":"unconfined","key":"kill_rule","ARGV":["0x29ca","0x9","0x0","0x7fbc297e1ac0"]},"PARENT_INFO":{"ARGV":["su","laura"],"ppid":8866},"OBJ_PID":[{"opid":10698,"oauid":1000,"ouid":1000,"oses":3,"obj":"unconfined","ocomm":"sleep"}],"PROCTITLE":{"ARGV":["bash"]}}
`

**Comment by AndyXan** [comment]
The automatic hex-decoding is only for the EXECVE Record-Type which comes along with the Record Type SYSCALL and the syscall number 59 for x64. What you have here is a Record-Type Syscall, where the values are indeed hex and the meaning depends on the actual syscall. For 62 (kill) the first argument, a0 for instance is the start address of the passed path name on your system. The rest follows from the definition: `int kill(pid_t pid, int sig);`. a1 is the pid you killed, a2 is the signal (9). a3 should be unused and is some random stack-addr.

If you're having a SYSCALL with value 59 (execve) the thing would be the same. However another Record Type (EXECVE) comes with it, where you can see the commandline. And this would in fact be decoded in laurel.

**Comment by hillu** [comment]
Closing this issue since the original question had apparently been answered.
