### ISSUE TITLE
Laurel 0.3.1 seems to have a memory leak.

### ISSUE THREAD

**Issue by adduali1310** [threathunters-io/laurel#75]
On testing out Laurel v0.3.1 on a Debian Bullseye Node with a 5.15.32 kernel, noticed a pretty significant upward curve in memory usage which keeps on incrementing without stabilizing, and seems indicative of a memory leak.

On running laurel with Valgrind, it flags some memory as being possibly lost.

```
==1524972== LEAK SUMMARY:
==1524972==    definitely lost: 0 bytes in 0 blocks
==1524972==    indirectly lost: 0 bytes in 0 blocks
==1524972==      possibly lost: 318 bytes in 7 blocks
==1524972==    still reachable: 298,337 bytes in 2,601 blocks
==1524972==         suppressed: 0 bytes in 0 blocks
```

From the Valgrind documentation:

Possibly lost". This means that a chain of one or more pointers to the block has been found, but at least one of the pointers is an interior-pointer. This could just be a random value in memory that happens to point into a block, and so you shouldn't consider this ok unless you know you have interior-pointers.

This seems to suggest that there is some memory that is not being freed accordingly. 

The CPU although increased after registering laurel as an auditd plugin, did stabilize soon after. But the memory just keeps on shooting up. Have also attached a few screenshots depicting the memory increase via Prometheus Metrics.

<img width="1698" alt="Screen Shot 2022-05-06 at 1 08 44 PM" src="https://user-images.githubusercontent.com/54876309/167194468-9d3e9fba-a52f-4c9d-a89b-561b6633e4f2.png">

 Laurel was deployed as an auditd plugin on 04/27/2022 in the above screenshot.

<img width="848" alt="Screen Shot 2022-05-06 at 1 15 20 PM" src="https://user-images.githubusercontent.com/54876309/167195294-2268b83f-89a1-401d-8557-a412f8e04e39.png">

On another machine, the memory aggressively shoots up within a few seconds.

Would like to hear any comments/opinions on this.

**Comment by hillu** [comment]
Oh, this does not look good. I had not seen this behavior before.

**Comment by hillu** [comment]
I have run Laurel on some example data using Valgrind and I have come to the conclusion that some memory leaks are related to usage of `lazy_static`. Could you repeat your Valgrind test with the `--leak-check=full` parameter?

Can you share your auditd configuration and ruleset and your laurel configuration?

**Comment by adduali1310** [comment]
The above attached valgrind output is with the --leak-check=full parameter enabled. Although for me the debug symbols seem to be stripped off, so not a lot of useful information there.

I have the following Valgrind options enabled:
```
--leak-check=full 
--leak-resolution=high 
--show-leak-kinds=definite,possible,reachable 
--show-reachable=yes 
--track-origins=yes 
--malloc-fill=1 
--free-fill=2 
--read-var-info=yes 
--log-file=valgrind.log
```
Would it be possible to share the example data you are using to debug this? What exact command and parameters are you using? Was it through this you were able to narrow it down to usage of `lazy_static` ?

I have attached the auditd config and the laurel config.
[auditd.conf.txt](https://github.com/threathunters-io/laurel/files/8656150/auditd.conf.txt)
[laurel.conf.txt](https://github.com/threathunters-io/laurel/files/8656168/laurel.conf.txt)


I won't be able to attach the auditd ruleset, but I doubt the ruleset matters in this case, because on running the syslog plugin with the same ruleset, I have no issues with the memory.

**Comment by hillu** [comment]
For my quick test, I used a debug build obtained by doing `cargo build` like this
```
valgrind --leak-check=full --gen-suppressions=no ./target/debug/laurel -c config-debug.toml < $FILE
```
Input files were taken from `src/testdata` and I also tried with log files that had been written by auditd.

Can you also post your audit ruleset? `auditctl -l` output should be fine.

**Comment by adduali1310** [comment]
Wanted to see if the issue was due to the ruleset. Just had the below single rule present and restarted the service.

`-w /etc -p wa `

Noticed a similar exponential increase in memory although at a much lower scale.

<img width="827" alt="Screen Shot 2022-05-20 at 9 42 58 AM" src="https://user-images.githubusercontent.com/54876309/169554035-8ccd43e5-0077-4d2e-9a68-8326b1afb540.png">



The logs are absolutely fine and produce the output in the JSON format as expected. No issues on the log side of things.

**Comment by hillu** [comment]
> Wanted to see if the issue was due to the ruleset. Just had the below single rule present and restarted the service.

Thank you very much. The graph does look interesting, there definitely is a pattern! What time difference does the space between two vertical bars in that graph represent?

Can you share some amount of raw audit logs generated from that simple `-w /etc -p wa` rule on the system where you ran this test?

**Comment by hillu** [comment]
> The time range of the above graph is about an hour.

Do you mean the range over all 8 segments?

> I am sorry but I will not be able to share the logs, although I would be happy to perform any other tests you would like.

No worries. I'm going to add that "dump internal state" feature in the next few days, perhaps we'll learn something from that.

**Comment by adduali1310** [comment]
> Do you mean the range over all 8 segments?

Yes, that is correct.

>No worries. I'm going to add that "dump internal state" feature in the next few days, perhaps we'll learn something from that.

Sounds good. Thanks.

**Comment by hillu** [comment]
@adduali1310 I have now implemented an option to periodically dump internal state to a debug log. It needs a bit of configuration:
``` toml
[debuglog]
file = "debug.log"

[debug]
dump-state-period = 120
```
Could you give it a try and see if there are any data structures on your affected system that keep growing?

**Comment by hillu** [comment]
@adduali1310 ping?

**Comment by hillu** [comment]
@adduali1310 ping?

**Comment by hillu** [comment]
@adduali1310 I am sorry. Since you haven't provided any information and I haven't observed memory leaks myself, there seems to be nothing I can do. I am closing this issue for now.

Should you change your mind, feel free to re-open the issue.
