### ISSUE TITLE
Laurel dont run with non local users

### ISSUE THREAD

**Issue by sraue** [threathunters-io/laurel#84]
We need to run laurel on systems where local users cant be created. Laurel seems to check /etc/passwd for users defined in config.toml  with `user=` and `read-users=`. If both (in our case) or one of this users are AD users laurel will not start:

`Jul 01 14:40:20 <hostname> /DATA/auditd/bin/laurel[129859]: user xxxxauditd not found`

Can support for non-local users be implemented?

```
# id xxxxauditd
uid=30019(xxxxauditd) gid=4305(xxx) groups=4305(xxx),4550(nopass01)
# id xxxxsplunk
uid=25581(xxxxsplunk) gid=4305(xxx) groups=4305(xxx),1290(suapache)
```

**Comment by disasmwinnie** [comment]
That should not happen, since the code does not access ``/etc/passwd`` directly, but via API. Could you please check whether you can resolve the user via ``getent passwd xxxxauditd``?
If not, my guess is that AD/LDAP is not configured correctly in ``/etc/nsswitch.conf``. If you use SSSD, its configs could also be a starting point.

Background: Laurel uses nix::unistd Rust crate for user/permission resolving. 
Under the hood it's the [getpwnam_r](https://github.com/nix-rust/nix/blob/0922fd99e7c8cbe7334754d712e8450c29d3d8e7/src/unistd.rs#L3102) function from libc, that is getting called eventually.
The [man(3) page](https://linux.die.net/man/3/getpwnam_r) explicitly states the resolution should work.

**Comment by hillu** [comment]
@sraue If you are using the binaries provided as part of our tagged Releases (or any other musl-libc-based builds), the name lookup code from musl-libc will be used. 

The obvious solution is building LAUREL from source, on a glibc-based system that matches the environment where you want to run it. (I'm considering adding prebuilt binaries, so you wouldn't need to.)

A workaround that would still allow you to use the statically-built, musl-libc-based binaries might be to use numeric values in the configuration file. (I have not tried this.)

**Comment by sraue** [comment]
Hi, many thanks for your help.

@hillu is right, i was using the prebuilt musl based build. Compiling the last release on a debian 11 system and using this on the target system seems to work. 

Afaik we are using RedHat, Centos and SuSE systems. Will there be problems using the same precompiled build on this various systems? actually i tested this on a SLES-15 system and it seems to work until now.

@hillu : if you can provide glibc based release builds in the future it would be very great!

Thanks much again.

**Comment by hillu** [comment]
@sraue The next release will include a non-static glibc-based build. It is performed on Debian/buster. I expect the resulting binary to work fine on other distros, too, provided that their glibc ia 2.18 or higher.

**Comment by hillu** [comment]
@sraue There might be another option: The _musl-libc_ [manual](https://musl.libc.org/doc/1.1.24/manual.html) that if a _nscd_ socket `/var/run/nscd/socket` exists, that can be used for user and group lookups, too.

So everything should work on systems where _nscd_ has been installed.

**Comment by sraue** [comment]
@hillu we are fine with providing the shared-lib based precompiled build. nscd will be no option for us, because we had some issues with this in the past. thanks again for your help and providing the builds.

**Comment by kugelman** [comment]
@hillu , we are running into the same issue here -- any idea when the next release is going to be cut? Having a lot of issues building from source :(

**Comment by hillu** [comment]
> @hillu , we are running into the same issue here -- any idea when the next release is going to be cut? Having a lot of issues building from source :(

oh well. I hope to do a 0.4.1 bugfix&performance release tomorrow morning (CEST).

**Comment by hillu** [comment]
@kugelman It took a bit longer, but the 0.4.1 release is out now. I hope that helps. :-)
