### ISSUE TITLE
Add option to replace UNIX epoch with ISO timestamp in log output

### ISSUE THREAD

**Issue by yorokobi** [threathunters-io/laurel#88]
This request is focused primarily on using Splunk as the target SIEM.

Splunk's time-series index files (TSIDX) create maps of "words" or segments to their frequency in the logs their associated with. The use of UNIX epoch time stamps creates a 1:1 mapping with the EventID's timestamp: each epoch value occurs (usually) only once. This will, with busy systems, create what are colloquially known as TSIDX explosions where the .tsidx files grow larger than the raw log data they correspond to.

To prevent this behaviour, it is recommended to use ISO timestamps (instead of UNIX epoch) values as their segmented components will occur more frequently, thus reducing the number of unique TSIDX entries.

As this request may not be useful for all scenarios, it can be something optionally enabled within the `config.toml` file. 

Example event (expanded with jq):

```json
{
 "ID": "199",
 "_time": "2022-08-07T17:39:25-0000",
 "SERVICE_STOP": {
   "pid": 1,
   "uid": 0,
   "auid": 4294967295,
   "ses": 4294967295,
   "subj": "system_u:system_r:init_t:s0",
   "msg": "unit=dnf-makecache comm=\"systemd\" exe=\"/usr/lib/systemd/systemd\" hostname=? addr=? terminal=? res=success",
   "UID": "root",
   "AUID": "unset"
 }
}
```

**Comment by hillu** [comment]
I think I understand the symptom you're describing. However, I don't understand how adding another field that happens to be a human-readable timestamp would fix the index bloat problem caused by the `ID` field. After all, the UNIX timestamps would still be there.

**Comment by yorokobi** [comment]
You are correct; I blinded myself to that with an assumption that the event ID might be needed as-is in some processing by a SIEM and didn't consider that (at least in Splunk), it can be re-created from the timestamp so long as the non-epoch portion is remains in the log output.

I am going to edit the original description and title to request the epoch value be removed, leaving the three digit portion as the "ID" field.

Funny thing: I kept coming back to this yesterday because something about it bothered me. Thank you for finding the flaw in my original request. 👍🏼

**Comment by hillu** [comment]
I don't want to **replace** parts of the event because we already use the ID as a sort of "foreign key" in the `PARENT_INFO` field.

Could we perhaps tell Splunk to avoid that index bloat for specific fields?

**Comment by yorokobi** [comment]
Yes, it certainly can. 

```
[auditd:json]
LINE_BREAKER = ([\r\n]+)
TIME_PREFIX = "ID":(\s+)?"
TIME_FORMAT = %s.%3N
MAX_TIMESTAMP_LOOKAHEAD = 15
SHOULD_LINEMERGE = false
#TRUNCATE = 10000
#TZ = UTC

### Remove UNIX epoch from _raw and leave the event ID. 
### The epoch value is preserved in the _time field
### extracted from the above TIME_* directives.
SEDCMD-no_epoch = s/"ID":(\s+)?"(\d{10}\.\d{3}:)/"ID":\1"/g
```

... in `props.conf` on the indexer(s) will alter the event to 

```json
{
  "ID": "346",
  "SERVICE_START": {
    "pid": 1,
    "uid": 0,
    "auid": 4294967295,
    "ses": 4294967295,
    "subj": "system_u:system_r:init_t:s0",
    "msg": "unit=SplunkForwarder comm=\"systemd\" exe=\"/usr/lib/systemd/systemd\" hostname=? addr=? terminal=? res=success",
    "UID": "root",
    "AUID": "unset"
  }
}
```

And `PARENT_INFO` is preserved for those events that have it.

**Comment by yorokobi** [comment]
Shower thought: I can submit a PR where the Splunk configs I used are added to contrib/ if you like.

A solution is available that solves the problem I was concerned about so I'll go ahead and close this issue.

**Comment by alexhaydock** [comment]
Apologies for reviving an old thread but I would greatly appreciate seeing the Splunk config you're using to ingest Laurel events @yorokobi if you'd be willing to post it.

Doesn't have to be within /contrib. Could be a separate repo or similar but it would be a great timesaver while I work on evaluating Laurel.

**Comment by yorokobi** [comment]
@alexhaydock The `props.conf` I proposed is already in this thread.

```ini
# inputs.conf
[monitor:///var/log/laurel/audit.log]
sourcetype = auditd:json
index = <you_choose>
```
