### ISSUE TITLE
what is the basic use of the tool

### ISSUE THREAD

**Issue by mospher** [threathunters-io/laurel#93]
How to parse the auditd Logs, For example, what commands need to be executed,  I didn't find help in the documentation，please advise

**Comment by hillu** [comment]
Installation is described in [INSTALL.md](https://github.com/threathunters-io/laurel/blob/master/INSTALL.md).

Is there anything missing?

**Comment by mospher** [comment]
thank u for your reply,
&nbsp; &nbsp; I mean that like the command " tail -100 /var/log/audit/audit.log  | laurel ; echo $?; cat audit.log " tell the machine to read lines from audit.log as the input of laurel, then laurel will write the json to ./audit.log.
&nbsp; &nbsp; The above description means a usage of the tool for me. There maybe no mention of that in the INSTALL.MD.
&nbsp; &nbsp; &nbsp;Your work is excellent, but I'm still in a very low grade, so hope you can understand what I mean.


 
---Original---
From: "Hilko ***@***.***&gt;
Date: 2022/8/20 00:46:17
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [threathunters-io/laurel] what is the basic use of the tool(Issue #93)




 
Installation is described in INSTALL.md.
 
Is there anything missing?

**Comment by hillu** [comment]
You're supposed to set up _auditd_ to pass the audit logs to _LAUREL_ as a plugin. _LAUREL_ will then write its own log file.

I think I described how to do that in the README.md and INSTALL.md documents. If there's anythig that is not clear after reading those files, I'd be grateful if you are able to suggest improvements.

**Comment by hillu** [comment]
@mospher I would have liked to talk about where the existing documentation may be lacking. If you'd like to contribute to such a discussion, feel free to reopen the issue at any time.

**Comment by mospher** [comment]
---Original---
From: "Hilko ***@***.***&gt;
Date: 2022/8/20 00:46:17
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [threathunters-io/laurel] what is the basic use of the tool(Issue #93)




 
Installation is described in INSTALL.md.
 
Is there anything missing?
